name: ssguan
version: 2
handlers:
- url: /static/
  static_path: static
- url: /favicon.ico
  static_path: static/favicon.ico
handle:
- compress:  if ( out_header["Content-type"] ~ "text/javascript" ) compress
- compress:  if ( out_header["Content-type"] ~ "text/html" ) compress