# -*- coding: utf-8 -*-

#  Copyright 2015 www.suishouguan.com
#
#  Licensed under the Private License (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      https://github.com/samuelbaizg/ssguan/blob/master/LICENSE
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
import conf
from contact.contacthandler import GroupListHandler, GroupSaveHandler, \
    GroupDeleteHandler, ContactListHandler, ContactSaveHandler, \
    ContactDeleteHandler, ContactRecoverHandler, ContactEmptyTrashHandler
from contact.contactmodel import Group, Contact, ContactGroup
from core import user
from core.migration import Version
from core.model import I18n, Operation, RoleOperation
from note.notehandler import     NotebookDeleteHandler, NotebookSaveHandler, NoteEmptyTrashHandler, \
     NotebookListHandler
from note.notehandler import NoteListHandler, NoteSaveHandler, NoteDeleteHandler, \
    NoteRecoverHandler
from note.notemodel import Note, Notebook
from task.taskhandler import WorksheetListHandler, WorksheetSaveHandler, \
    WorksheetDeleteHandler, TaskListHandler, TaskEmptyTrashHandler, \
    TaskRecoverHandler, TaskDeleteHandler, TaskSaveHandler, \
    TaskCommentSaveHandler
from task.taskmodel import Worksheet, TaskComment, Task


class V1(Version):
    
    def _upgrade(self, modifier_id):
        Note.create_table()
        Notebook.create_table()
        
        Group.create_table()
        Contact.create_table()
        ContactGroup.create_table()
        
        Task.create_table()
        Worksheet.create_table()
        TaskComment.create_table()
        
    def _downgrade(self, modifier_id):
        Note.delete_table()
        Notebook.delete_table()
        Group.delete_table()
        Contact.delete_table()
        ContactGroup.delete_table()
        Task.delete_table()
        Worksheet.delete_table()
        TaskComment.delete_table()
            
    def _get_roles(self):
        return []
    
    def _get_operations(self):
        operations = []
        operations.append(Operation(operation_key="NOTE_NOTEBOOKLIST", handler_classes=NotebookListHandler.get_qualified_name(), resource_oql=None))
        operations.append(Operation(operation_key="NOTE_NOTEBOOKEDIT", handler_classes=NotebookSaveHandler.get_qualified_name(), resource_oql=None))
        operations.append(Operation(operation_key="NOTE_NOTEBOOKDELETE", handler_classes=NotebookDeleteHandler.get_qualified_name(), resource_oql=None))
        operations.append(Operation(operation_key="NOTE_NOTELIST", handler_classes=NoteListHandler.get_qualified_name(), resource_oql=None))
        operations.append(Operation(operation_key="NOTE_NOTEEDIT", handler_classes=NoteSaveHandler.get_qualified_name(), resource_oql=None))
        operations.append(Operation(operation_key="NOTE_NOTEDELETE", handler_classes=NoteDeleteHandler.get_qualified_name(), resource_oql=None))
        operations.append(Operation(operation_key="NOTE_NOTERECOVER", handler_classes=NoteRecoverHandler.get_qualified_name(), resource_oql=None))
        operations.append(Operation(operation_key="NOTE_EMPTYTRASH", handler_classes=NoteEmptyTrashHandler.get_qualified_name(), resource_oql=None))
        
        operations.append(Operation(operation_key="CONTACT_GROUPLIST", handler_classes=GroupListHandler.get_qualified_name(), resource_oql=None))
        operations.append(Operation(operation_key="CONTACT_GROUPEDIT", handler_classes=GroupSaveHandler.get_qualified_name(), resource_oql=None))
        operations.append(Operation(operation_key="CONTACT_GROUPDELETE", handler_classes=GroupDeleteHandler.get_qualified_name(), resource_oql=None))
        operations.append(Operation(operation_key="CONTACT_CONTACTLIST", handler_classes=ContactListHandler.get_qualified_name(), resource_oql=None))
        operations.append(Operation(operation_key="CONTACT_CONTACTEDIT", handler_classes=ContactSaveHandler.get_qualified_name(), resource_oql=None))
        operations.append(Operation(operation_key="CONTACT_CONTACTDELETE", handler_classes=ContactDeleteHandler.get_qualified_name(), resource_oql=None))
        operations.append(Operation(operation_key="CONTACT_CONTACTRECOVER", handler_classes=ContactRecoverHandler.get_qualified_name(), resource_oql=None))
        operations.append(Operation(operation_key="CONTACT_EMPTYTRASH", handler_classes=ContactEmptyTrashHandler.get_qualified_name(), resource_oql=None))
        
        operations.append(Operation(operation_key="TASK_WORKSHEETLIST", handler_classes=WorksheetListHandler.get_qualified_name(), resource_oql=None))
        operations.append(Operation(operation_key="TASK_WORKSHEETEDIT", handler_classes=WorksheetSaveHandler.get_qualified_name(), resource_oql=None))
        operations.append(Operation(operation_key="TASK_WORKSHEETDELETE", handler_classes=WorksheetDeleteHandler.get_qualified_name(), resource_oql=None))
        operations.append(Operation(operation_key="TASK_TASKLIST", handler_classes=TaskListHandler.get_qualified_name(), resource_oql=None))
        operations.append(Operation(operation_key="TASK_TASKEDIT", handler_classes=TaskSaveHandler.get_qualified_name(), resource_oql=None))
        operations.append(Operation(operation_key="TASK_TASKDELETE", handler_classes=TaskDeleteHandler.get_qualified_name(), resource_oql=None))
        operations.append(Operation(operation_key="TASK_TASKRECOVER", handler_classes=TaskRecoverHandler.get_qualified_name(), resource_oql=None))
        operations.append(Operation(operation_key="TASK_EMPTYTRASH", handler_classes=TaskEmptyTrashHandler.get_qualified_name(), resource_oql=None))
        operations.append(Operation(operation_key="TASK_TASKCOMMENTSAVE", handler_classes=TaskCommentSaveHandler.get_qualified_name(), resource_oql=None))
        
        return operations
    
    def _get_roleoperations(self):
        roleoperations = []
        ordinary_role = user.get_role(role_name="Ordinary User")
        roleoperations.append(RoleOperation(role_id=ordinary_role.uid, operation_key="NOTE_NOTEBOOKLIST"))
        roleoperations.append(RoleOperation(role_id=ordinary_role.uid, operation_key="NOTE_NOTEBOOKEDIT"))
        roleoperations.append(RoleOperation(role_id=ordinary_role.uid, operation_key="NOTE_NOTEBOOKDELETE"))
        roleoperations.append(RoleOperation(role_id=ordinary_role.uid, operation_key="NOTE_NOTELIST"))
        roleoperations.append(RoleOperation(role_id=ordinary_role.uid, operation_key="NOTE_NOTEEDIT"))
        roleoperations.append(RoleOperation(role_id=ordinary_role.uid, operation_key="NOTE_NOTEDELETE"))
        roleoperations.append(RoleOperation(role_id=ordinary_role.uid, operation_key="NOTE_NOTERECOVER"))
        roleoperations.append(RoleOperation(role_id=ordinary_role.uid, operation_key="NOTE_EMPTYTRASH"))
        
        roleoperations.append(RoleOperation(role_id=ordinary_role.uid, operation_key="CONTACT_GROUPLIST"))
        roleoperations.append(RoleOperation(role_id=ordinary_role.uid, operation_key="CONTACT_GROUPEDIT"))
        roleoperations.append(RoleOperation(role_id=ordinary_role.uid, operation_key="CONTACT_GROUPDELETE"))
        roleoperations.append(RoleOperation(role_id=ordinary_role.uid, operation_key="CONTACT_CONTACTLIST"))
        roleoperations.append(RoleOperation(role_id=ordinary_role.uid, operation_key="CONTACT_CONTACTEDIT"))
        roleoperations.append(RoleOperation(role_id=ordinary_role.uid, operation_key="CONTACT_CONTACTDELETE"))
        roleoperations.append(RoleOperation(role_id=ordinary_role.uid, operation_key="CONTACT_CONTACTRECOVER"))
        roleoperations.append(RoleOperation(role_id=ordinary_role.uid, operation_key="CONTACT_EMPTYTRASH"))
        
        roleoperations.append(RoleOperation(role_id=ordinary_role.uid, operation_key="TASK_WORKSHEETLIST"))
        roleoperations.append(RoleOperation(role_id=ordinary_role.uid, operation_key="TASK_WORKSHEETEDIT"))
        roleoperations.append(RoleOperation(role_id=ordinary_role.uid, operation_key="TASK_WORKSHEETDELETE"))
        roleoperations.append(RoleOperation(role_id=ordinary_role.uid, operation_key="TASK_TASKLIST"))
        roleoperations.append(RoleOperation(role_id=ordinary_role.uid, operation_key="TASK_TASKEDIT"))
        roleoperations.append(RoleOperation(role_id=ordinary_role.uid, operation_key="TASK_TASKDELETE"))
        roleoperations.append(RoleOperation(role_id=ordinary_role.uid, operation_key="TASK_TASKRECOVER"))
        roleoperations.append(RoleOperation(role_id=ordinary_role.uid, operation_key="TASK_EMPTYTRASH"))
        roleoperations.append(RoleOperation(role_id=ordinary_role.uid, operation_key="TASK_TASKCOMMENTSAVE"))
        
        return roleoperations
    
    def _get_i18ns(self):
        i18ns = []
        
        i18ns.append(I18n(i1_key="app_title", i1_locale=conf.LANG_EN, i1_message=u"Handyman - GTD Tools"))
        i18ns.append(I18n(i1_key="app_title", i1_locale=conf.LANG_ZH_CN, i1_message=u"随手管-无压工作，无压生活"))
        i18ns.append(I18n(i1_key="app_description", i1_locale=conf.LANG_EN, i1_message=u"Handyman - GTD Tools"))
        i18ns.append(I18n(i1_key="app_description", i1_locale=conf.LANG_ZH_CN, i1_message=u"随手管-无压工作，无压生活"))

        i18ns.append(I18n(i1_key="cont_label_contactmodule", i1_locale=conf.LANG_EN, i1_message=u"Contact"))
        i18ns.append(I18n(i1_key="cont_label_contactmodule", i1_locale=conf.LANG_ZH_CN, i1_message=u"联系人"))
        i18ns.append(I18n(i1_key="task_label_taskmodule", i1_locale=conf.LANG_EN, i1_message=u"Task"))
        i18ns.append(I18n(i1_key="task_label_taskmodule", i1_locale=conf.LANG_ZH_CN, i1_message=u"工作"))
        
        i18ns.append(I18n(i1_key="note_label_notemodule", i1_locale=conf.LANG_EN, i1_message=u"Notebook"))
        i18ns.append(I18n(i1_key="note_label_notemodule", i1_locale=conf.LANG_ZH_CN, i1_message=u"笔记"))
        i18ns.append(I18n(i1_key="note_label_notebook", i1_locale=conf.LANG_EN, i1_message=u"NOTEBOOK"))
        i18ns.append(I18n(i1_key="note_label_notebook", i1_locale=conf.LANG_ZH_CN, i1_message=u"笔记本"))
        i18ns.append(I18n(i1_key="note_label_note", i1_locale=conf.LANG_EN, i1_message=u"NOTE"))
        i18ns.append(I18n(i1_key="note_label_note", i1_locale=conf.LANG_ZH_CN, i1_message=u"笔记"))
        i18ns.append(I18n(i1_key="note_label_notesearch", i1_locale=conf.LANG_EN, i1_message=u"Search Note"))
        i18ns.append(I18n(i1_key="note_label_notesearch", i1_locale=conf.LANG_ZH_CN, i1_message=u"搜索笔记"))
        i18ns.append(I18n(i1_key="note_label_notebookname", i1_locale=conf.LANG_EN, i1_message=u"Notebook Name"))
        i18ns.append(I18n(i1_key="note_label_notebookname", i1_locale=conf.LANG_ZH_CN, i1_message=u"笔记本名称"))
        i18ns.append(I18n(i1_key="note_label_notebookorder", i1_locale=conf.LANG_EN, i1_message=u"Notebook Order"))
        i18ns.append(I18n(i1_key="note_label_notebookorder", i1_locale=conf.LANG_ZH_CN, i1_message=u"显示顺序"))
        i18ns.append(I18n(i1_key="note_label_recyclebin", i1_locale=conf.LANG_EN, i1_message=u"Recycle Bin"))
        i18ns.append(I18n(i1_key="note_label_recyclebin", i1_locale=conf.LANG_ZH_CN, i1_message=u"回收站"))
        i18ns.append(I18n(i1_key="note_label_mynotebooks", i1_locale=conf.LANG_EN, i1_message=u"My Notebooks"))
        i18ns.append(I18n(i1_key="note_label_mynotebooks", i1_locale=conf.LANG_ZH_CN, i1_message=u"我的笔记本"))
        i18ns.append(I18n(i1_key="note_label_defaultnotebook", i1_locale=conf.LANG_EN, i1_message=u"Default Notebook"))
        i18ns.append(I18n(i1_key="note_label_defaultnotebook", i1_locale=conf.LANG_ZH_CN, i1_message=u"默认笔记本"))
        i18ns.append(I18n(i1_key="note_label_notesubject", i1_locale=conf.LANG_EN, i1_message=u"Note Subject"))
        i18ns.append(I18n(i1_key="note_label_notesubject", i1_locale=conf.LANG_ZH_CN, i1_message=u"笔记标题"))
        i18ns.append(I18n(i1_key="note_label_notecontent", i1_locale=conf.LANG_EN, i1_message=u"Note Content"))
        i18ns.append(I18n(i1_key="note_label_notecontent", i1_locale=conf.LANG_ZH_CN, i1_message=u"笔记内容"))
        i18ns.append(I18n(i1_key="note_label_notebookkey", i1_locale=conf.LANG_EN, i1_message=u"Notebook Key"))
        i18ns.append(I18n(i1_key="note_label_notebookkey", i1_locale=conf.LANG_ZH_CN, i1_message=u"笔记本Key"))
        
        i18ns.append(I18n(i1_key="note_action_addnote", i1_locale=conf.LANG_EN, i1_message=u"Add Note"))
        i18ns.append(I18n(i1_key="note_action_addnote", i1_locale=conf.LANG_ZH_CN, i1_message=u"新建笔记"))
        i18ns.append(I18n(i1_key="note_action_emptyrecyclebin", i1_locale=conf.LANG_EN, i1_message=u"Empty Recycle Bin"))
        i18ns.append(I18n(i1_key="note_action_emptyrecyclebin", i1_locale=conf.LANG_ZH_CN, i1_message=u"清空回收站"))
        i18ns.append(I18n(i1_key="note_action_addnotebook", i1_locale=conf.LANG_EN, i1_message=u"Add Notebook"))
        i18ns.append(I18n(i1_key="note_action_addnotebook", i1_locale=conf.LANG_ZH_CN, i1_message=u"新建笔记本"))
        i18ns.append(I18n(i1_key="note_action_updatenotebook", i1_locale=conf.LANG_EN, i1_message=u"Rename Notebook"))
        i18ns.append(I18n(i1_key="note_action_updatenotebook", i1_locale=conf.LANG_ZH_CN, i1_message=u"重命名笔记本"))
        i18ns.append(I18n(i1_key="note_action_deletenotebook", i1_locale=conf.LANG_EN, i1_message=u"Delete Notebook"))
        i18ns.append(I18n(i1_key="note_action_deletenotebook", i1_locale=conf.LANG_ZH_CN, i1_message=u"删除笔记本"))
        i18ns.append(I18n(i1_key="note_action_recovernote", i1_locale=conf.LANG_EN, i1_message=u"Recover Note"))
        i18ns.append(I18n(i1_key="note_action_recovernote", i1_locale=conf.LANG_ZH_CN, i1_message=u"恢复笔记"))
        i18ns.append(I18n(i1_key="note_action_permanentdelete", i1_locale=conf.LANG_EN, i1_message=u"Permanent Delete Note"))
        i18ns.append(I18n(i1_key="note_action_permanentdelete", i1_locale=conf.LANG_ZH_CN, i1_message=u"永久删除笔记"))
        
        i18ns.append(I18n(i1_key="note_confirm_emptyrecyclebin", i1_locale=conf.LANG_EN, i1_message=u"Do you confirm to clear up recycle bin ?"))
        i18ns.append(I18n(i1_key="note_confirm_emptyrecyclebin", i1_locale=conf.LANG_ZH_CN, i1_message=u"你确定要清空回收站吗？"))
        i18ns.append(I18n(i1_key="note_confirm_deletenote", i1_locale=conf.LANG_EN, i1_message=u"Do you confirm to delete this note ?"))
        i18ns.append(I18n(i1_key="note_confirm_deletenote", i1_locale=conf.LANG_ZH_CN, i1_message=u"你确定要删除这个笔记吗？"))
        i18ns.append(I18n(i1_key="note_confirm_permanentdeletenote", i1_locale=conf.LANG_EN, i1_message=u"Do you confirm to delete this note permanently ?"))
        i18ns.append(I18n(i1_key="note_confirm_permanentdeletenote", i1_locale=conf.LANG_ZH_CN, i1_message=u"你确定要永久删除这个笔记吗？"))
        i18ns.append(I18n(i1_key="note_confirm_movenote", i1_locale=conf.LANG_EN, i1_message=u"Do you confirm to move this note to notebook {{notebook}}?"))
        i18ns.append(I18n(i1_key="note_confirm_movenote", i1_locale=conf.LANG_ZH_CN, i1_message=u"你确定要移动这个笔记到{{notebook}}吗？"))
        i18ns.append(I18n(i1_key="note_confirm_recovernote", i1_locale=conf.LANG_EN, i1_message=u"Do you confirm to recover this note to notebook {{notebook}}?"))
        i18ns.append(I18n(i1_key="note_confirm_recovernote", i1_locale=conf.LANG_ZH_CN, i1_message=u"你确定要恢复这个笔记到{{notebook}}吗？"))
        i18ns.append(I18n(i1_key="note_confirm_emptytrash", i1_locale=conf.LANG_EN, i1_message=u"Do you confirm to empty the recycle bin ?"))
        i18ns.append(I18n(i1_key="note_confirm_emptytrash", i1_locale=conf.LANG_ZH_CN, i1_message=u"你确定要清空回收站吗？"))
        
        i18ns.append(I18n(i1_key="note_confirm_notebook_delete", i1_locale=conf.LANG_EN, i1_message=u"The notes in this notebook will be deleted also, do you confirm to delete this notebook."))
        i18ns.append(I18n(i1_key="note_confirm_notebook_delete", i1_locale=conf.LANG_ZH_CN, i1_message=u"笔记本中的笔记将被同步删除， 你确认要删除吗？"))
        i18ns.append(I18n(i1_key="note_error_trashed_update", i1_locale=conf.LANG_EN, i1_message=u"You can't update the notes which are in trash."))
        i18ns.append(I18n(i1_key="note_error_trashed_update", i1_locale=conf.LANG_ZH_CN, i1_message=u"笔记在回收站中，不能编辑！"))
        i18ns.append(I18n(i1_key="note_error_pendingsave", i1_locale=conf.LANG_EN, i1_message=u"Note is not saved, please save first then go to another note."))
        i18ns.append(I18n(i1_key="note_error_pendingsave", i1_locale=conf.LANG_ZH_CN, i1_message=u"笔记还没有保存，请先保存笔记，再切换到其它笔记！"))
        
        i18ns.append(I18n(i1_key="cont_label_group", i1_locale=conf.LANG_EN, i1_message=u"Contact Group"))
        i18ns.append(I18n(i1_key="cont_label_group", i1_locale=conf.LANG_ZH_CN, i1_message=u"联系人分组"))
        i18ns.append(I18n(i1_key="cont_label_contact", i1_locale=conf.LANG_EN, i1_message=u"Contact"))
        i18ns.append(I18n(i1_key="cont_label_contact", i1_locale=conf.LANG_ZH_CN, i1_message=u"联系人"))
        i18ns.append(I18n(i1_key="cont_label_contactsearch", i1_locale=conf.LANG_EN, i1_message=u"Search Contact"))
        i18ns.append(I18n(i1_key="cont_label_contactsearch", i1_locale=conf.LANG_ZH_CN, i1_message=u"搜索联系人"))
        i18ns.append(I18n(i1_key="cont_label_groupkey", i1_locale=conf.LANG_EN, i1_message=u"Contact Group Key"))
        i18ns.append(I18n(i1_key="cont_label_groupkey", i1_locale=conf.LANG_ZH_CN, i1_message=u"联系人分组Key"))
        i18ns.append(I18n(i1_key="cont_label_contactkey", i1_locale=conf.LANG_EN, i1_message="Contact Key"))
        i18ns.append(I18n(i1_key="cont_label_contactkey", i1_locale=conf.LANG_ZH_CN, i1_message=u"联系人Key"))
        i18ns.append(I18n(i1_key="cont_label_mygroups", i1_locale=conf.LANG_EN, i1_message=u"My Groups"))
        i18ns.append(I18n(i1_key="cont_label_mygroups", i1_locale=conf.LANG_ZH_CN, i1_message=u"我的联系人分组"))
        i18ns.append(I18n(i1_key="cont_label_companymime", i1_locale=conf.LANG_EN, i1_message=u"Company"))
        i18ns.append(I18n(i1_key="cont_label_companymime", i1_locale=conf.LANG_ZH_CN, i1_message=u"单位"))
        i18ns.append(I18n(i1_key="cont_label_mobilephonemime", i1_locale=conf.LANG_EN, i1_message=u"Mobile and Phone"))
        i18ns.append(I18n(i1_key="cont_label_mobilephonemime", i1_locale=conf.LANG_ZH_CN, i1_message=u"手机与电话"))
        i18ns.append(I18n(i1_key="cont_label_emailmime", i1_locale=conf.LANG_EN, i1_message=u"Email"))
        i18ns.append(I18n(i1_key="cont_label_emailmime", i1_locale=conf.LANG_ZH_CN, i1_message=u"电子邮件"))
        i18ns.append(I18n(i1_key="cont_label_imsomime", i1_locale=conf.LANG_EN, i1_message=u"IM and Social"))
        i18ns.append(I18n(i1_key="cont_label_imsomime", i1_locale=conf.LANG_ZH_CN, i1_message=u"即时通信与社交"))
        i18ns.append(I18n(i1_key="cont_label_othermime", i1_locale=conf.LANG_EN, i1_message=u"Other"))
        i18ns.append(I18n(i1_key="cont_label_othermime", i1_locale=conf.LANG_ZH_CN, i1_message=u"其它"))
        
        i18ns.append(I18n(i1_key="cont_label_contactname", i1_locale=conf.LANG_EN, i1_message=u"Contact Name"))
        i18ns.append(I18n(i1_key="cont_label_contactname", i1_locale=conf.LANG_ZH_CN, i1_message=u"姓名"))
        i18ns.append(I18n(i1_key="cont_label_birthday", i1_locale=conf.LANG_EN, i1_message=u"Birthday"))
        i18ns.append(I18n(i1_key="cont_label_birthday", i1_locale=conf.LANG_ZH_CN, i1_message=u"生日"))
        
        i18ns.append(I18n(i1_key="cont_label_emailwork", i1_locale=conf.LANG_EN, i1_message=u"Email Work"))
        i18ns.append(I18n(i1_key="cont_label_emailwork", i1_locale=conf.LANG_ZH_CN, i1_message=u"工作Email"))
        i18ns.append(I18n(i1_key="cont_label_emailhome", i1_locale=conf.LANG_EN, i1_message=u"Email Home"))
        i18ns.append(I18n(i1_key="cont_label_emailhome", i1_locale=conf.LANG_ZH_CN, i1_message=u"私人Email"))
        i18ns.append(I18n(i1_key="cont_label_mobilebusiness", i1_locale=conf.LANG_EN, i1_message=u"Business"))
        i18ns.append(I18n(i1_key="cont_label_mobilebusiness", i1_locale=conf.LANG_ZH_CN, i1_message=u"工作手机"))
        i18ns.append(I18n(i1_key="cont_label_mobileprivate", i1_locale=conf.LANG_EN, i1_message=u"Private"))
        i18ns.append(I18n(i1_key="cont_label_mobileprivate", i1_locale=conf.LANG_ZH_CN, i1_message=u"个人手机"))
        i18ns.append(I18n(i1_key="cont_label_phoneoffice", i1_locale=conf.LANG_EN, i1_message=u"Office"))
        i18ns.append(I18n(i1_key="cont_label_phoneoffice", i1_locale=conf.LANG_ZH_CN, i1_message=u"办公电话"))
        i18ns.append(I18n(i1_key="cont_label_phonehome", i1_locale=conf.LANG_EN, i1_message=u"Home"))
        i18ns.append(I18n(i1_key="cont_label_phonehome", i1_locale=conf.LANG_ZH_CN, i1_message=u"住宅电话"))
        i18ns.append(I18n(i1_key="cont_label_faxoffice", i1_locale=conf.LANG_EN, i1_message=u"Fax Office"))
        i18ns.append(I18n(i1_key="cont_label_faxoffice", i1_locale=conf.LANG_ZH_CN, i1_message=u"单位传真"))
        i18ns.append(I18n(i1_key="cont_label_company", i1_locale=conf.LANG_EN, i1_message=u"Company"))
        i18ns.append(I18n(i1_key="cont_label_company", i1_locale=conf.LANG_ZH_CN, i1_message=u"单位名称"))
        i18ns.append(I18n(i1_key="cont_label_position", i1_locale=conf.LANG_EN, i1_message=u"Position"))
        i18ns.append(I18n(i1_key="cont_label_position", i1_locale=conf.LANG_ZH_CN, i1_message=u"职位/角色"))
        i18ns.append(I18n(i1_key="cont_label_department", i1_locale=conf.LANG_EN, i1_message=u"Department"))
        i18ns.append(I18n(i1_key="cont_label_department", i1_locale=conf.LANG_ZH_CN, i1_message=u"部门名称"))
        i18ns.append(I18n(i1_key="cont_label_imqq", i1_locale=conf.LANG_EN, i1_message=u"QQ"))
        i18ns.append(I18n(i1_key="cont_label_imqq", i1_locale=conf.LANG_ZH_CN, i1_message=u"QQ"))
        i18ns.append(I18n(i1_key="cont_label_soweixin", i1_locale=conf.LANG_EN, i1_message=u"Weixin"))
        i18ns.append(I18n(i1_key="cont_label_soweixin", i1_locale=conf.LANG_ZH_CN, i1_message=u"微信"))
        i18ns.append(I18n(i1_key="cont_label_soweibo", i1_locale=conf.LANG_EN, i1_message=u"Sina Webo"))
        i18ns.append(I18n(i1_key="cont_label_soweibo", i1_locale=conf.LANG_ZH_CN, i1_message=u"新浪微博"))
        i18ns.append(I18n(i1_key="cont_label_imskype", i1_locale=conf.LANG_EN, i1_message=u"Skype"))
        i18ns.append(I18n(i1_key="cont_label_imskype", i1_locale=conf.LANG_ZH_CN, i1_message=u"Skype"))
        i18ns.append(I18n(i1_key="cont_label_remark", i1_locale=conf.LANG_EN, i1_message=u"Remark"))
        i18ns.append(I18n(i1_key="cont_label_remark", i1_locale=conf.LANG_ZH_CN, i1_message=u"备注"))
        i18ns.append(I18n(i1_key="cont_label_defaultgroup", i1_locale=conf.LANG_EN, i1_message=u"Default Group"))
        i18ns.append(I18n(i1_key="cont_label_defaultgroup", i1_locale=conf.LANG_ZH_CN, i1_message=u"默认联系人分组"))
        i18ns.append(I18n(i1_key="cont_label_recyclebin", i1_locale=conf.LANG_EN, i1_message=u"Recycle Bin"))
        i18ns.append(I18n(i1_key="cont_label_recyclebin", i1_locale=conf.LANG_ZH_CN, i1_message=u"回收站"))
        i18ns.append(I18n(i1_key="cont_label_contactgroups", i1_locale=conf.LANG_EN, i1_message=u"Contact Groups"))
        i18ns.append(I18n(i1_key="cont_label_contactgroups", i1_locale=conf.LANG_ZH_CN, i1_message=u"联系人所属分组"))
        i18ns.append(I18n(i1_key="cont_label_groupname", i1_locale=conf.LANG_EN, i1_message=u"Contact Group Name"))
        i18ns.append(I18n(i1_key="cont_label_groupname", i1_locale=conf.LANG_ZH_CN, i1_message=u"联系人分组名称"))
        
        i18ns.append(I18n(i1_key="cont_action_addgroup", i1_locale=conf.LANG_EN, i1_message=u"Add Group"))
        i18ns.append(I18n(i1_key="cont_action_addgroup", i1_locale=conf.LANG_ZH_CN, i1_message=u"新建联系人分组"))
        i18ns.append(I18n(i1_key="cont_action_updategroup", i1_locale=conf.LANG_EN, i1_message=u"Update Group"))
        i18ns.append(I18n(i1_key="cont_action_updategroup", i1_locale=conf.LANG_ZH_CN, i1_message=u"修改联系人分组"))
        i18ns.append(I18n(i1_key="cont_action_deletegroup", i1_locale=conf.LANG_EN, i1_message=u"Delete Group"))
        i18ns.append(I18n(i1_key="cont_action_deletegroup", i1_locale=conf.LANG_ZH_CN, i1_message=u"删除联系人分组"))
        i18ns.append(I18n(i1_key="cont_action_addcontact", i1_locale=conf.LANG_EN, i1_message=u"Add Contact"))
        i18ns.append(I18n(i1_key="cont_action_addcontact", i1_locale=conf.LANG_ZH_CN, i1_message=u"新建联系人"))
        i18ns.append(I18n(i1_key="cont_action_updatecontact", i1_locale=conf.LANG_EN, i1_message=u"Update Contact"))
        i18ns.append(I18n(i1_key="cont_action_updatecontact", i1_locale=conf.LANG_ZH_CN, i1_message=u"修改联系人"))
        i18ns.append(I18n(i1_key="cont_action_deletecontact", i1_locale=conf.LANG_EN, i1_message=u"Delete Contact"))
        i18ns.append(I18n(i1_key="cont_action_deletecontact", i1_locale=conf.LANG_ZH_CN, i1_message=u"删除联系人"))
        i18ns.append(I18n(i1_key="cont_action_recovercontact", i1_locale=conf.LANG_EN, i1_message=u"Recover Contact"))
        i18ns.append(I18n(i1_key="cont_action_recovercontact", i1_locale=conf.LANG_ZH_CN, i1_message=u"恢复联系人"))
        i18ns.append(I18n(i1_key="cont_action_permanentdelete", i1_locale=conf.LANG_EN, i1_message=u"Permanent Delete Contact"))
        i18ns.append(I18n(i1_key="cont_action_permanentdelete", i1_locale=conf.LANG_ZH_CN, i1_message=u"永久删除联系人"))
        i18ns.append(I18n(i1_key="cont_action_emptytrash", i1_locale=conf.LANG_EN, i1_message=u"Empty Recycle Bin"))
        i18ns.append(I18n(i1_key="cont_action_emptytrash", i1_locale=conf.LANG_ZH_CN, i1_message=u"清空回收站"))
        
        i18ns.append(I18n(i1_key="cont_confirm_emptyrecyclebin", i1_locale=conf.LANG_EN, i1_message=u"Do you confirm to clear up recycle bin ?"))
        i18ns.append(I18n(i1_key="cont_confirm_emptyrecyclebin", i1_locale=conf.LANG_ZH_CN, i1_message=u"你确定要清空回收站吗？"))
        i18ns.append(I18n(i1_key="cont_confirm_deletegroup", i1_locale=conf.LANG_EN, i1_message=u"Do you confirm to delete this contact group ?"))
        i18ns.append(I18n(i1_key="cont_confirm_deletegroup", i1_locale=conf.LANG_ZH_CN, i1_message=u"你确定要删除这个联系人分组吗？"))
        i18ns.append(I18n(i1_key="cont_confirm_deletecontact", i1_locale=conf.LANG_EN, i1_message=u"Do you confirm to delete this contact ?"))
        i18ns.append(I18n(i1_key="cont_confirm_deletecontact", i1_locale=conf.LANG_ZH_CN, i1_message=u"你确定要删除这个联系人吗？"))
        i18ns.append(I18n(i1_key="cont_confirm_permanentdelete", i1_locale=conf.LANG_EN, i1_message=u"Do you confirm to delete this contact {{contact}} permanently ?"))
        i18ns.append(I18n(i1_key="cont_confirm_permanentdelete", i1_locale=conf.LANG_ZH_CN, i1_message=u"你确定要永久删除联系人{{contact}}吗？"))
        i18ns.append(I18n(i1_key="cont_confirm_movecontact", i1_locale=conf.LANG_EN, i1_message=u"Do you confirm to move this contact to groups ?"))
        i18ns.append(I18n(i1_key="cont_confirm_movecontact", i1_locale=conf.LANG_ZH_CN, i1_message=u"你确定要移动这个联系人到{{groups}}吗？"))
        i18ns.append(I18n(i1_key="cont_confirm_recovercontact", i1_locale=conf.LANG_EN, i1_message=u"Do you confirm to recover this contact?"))
        i18ns.append(I18n(i1_key="cont_confirm_recovercontact", i1_locale=conf.LANG_ZH_CN, i1_message=u"你确定要恢复这个联系人吗？"))
        i18ns.append(I18n(i1_key="cont_confirm_emptytrash", i1_locale=conf.LANG_EN, i1_message=u"Do you confirm to empty the recycle bin ?"))
        i18ns.append(I18n(i1_key="cont_confirm_emptytrash", i1_locale=conf.LANG_ZH_CN, i1_message=u"你确定要清空回收站吗？"))
        i18ns.append(I18n(i1_key="cont_error_trashedupdate", i1_locale=conf.LANG_EN, i1_message=u"You can't update the contacts which are in trash."))
        i18ns.append(I18n(i1_key="cont_error_trashedupdate", i1_locale=conf.LANG_ZH_CN, i1_message=u"联系人在回收站，不能修改."))
        i18ns.append(I18n(i1_key="cont_error_pendingsave", i1_locale=conf.LANG_EN, i1_message=u"Contact is not saved, please save first then go to another contact."))
        i18ns.append(I18n(i1_key="cont_error_pendingsave", i1_locale=conf.LANG_ZH_CN, i1_message=u"联系人还没有保存，请先保存联系人再切换到其他联系人！"))
        
        i18ns.append(I18n(i1_key="task_code_open", i1_locale=conf.LANG_EN, i1_message=u"Open", i1_type="task_status_code"))
        i18ns.append(I18n(i1_key="task_code_open", i1_locale=conf.LANG_ZH_CN, i1_message=u"未开始", i1_type="task_status_code"))
        i18ns.append(I18n(i1_key="task_code_inprogress", i1_locale=conf.LANG_EN, i1_message=u"In Progress", i1_type="task_status_code"))
        i18ns.append(I18n(i1_key="task_code_inprogress", i1_locale=conf.LANG_ZH_CN, i1_message=u"进行中", i1_type="task_status_code"))
        i18ns.append(I18n(i1_key="task_code_closed", i1_locale=conf.LANG_EN, i1_message=u"Closed", i1_type="task_status_code"))        
        i18ns.append(I18n(i1_key="task_code_closed", i1_locale=conf.LANG_ZH_CN, i1_message=u"已完成", i1_type="task_status_code"))        
        i18ns.append(I18n(i1_key="task_code_suspended", i1_locale=conf.LANG_EN, i1_message=u"Suspended", i1_type="task_status_code"))
        i18ns.append(I18n(i1_key="task_code_suspended", i1_locale=conf.LANG_ZH_CN, i1_message=u"暂停", i1_type="task_status_code"))
        i18ns.append(I18n(i1_key="task_code_blocked", i1_locale=conf.LANG_EN, i1_message=u"Blocked", i1_type="task_status_code"))
        i18ns.append(I18n(i1_key="task_code_blocked", i1_locale=conf.LANG_ZH_CN, i1_message=u"等待别人", i1_type="task_status_code"))
        i18ns.append(I18n(i1_key="task_code_cancel", i1_locale=conf.LANG_EN, i1_message=u"Cancel", i1_type="task_status_code"))
        i18ns.append(I18n(i1_key="task_code_cancel", i1_locale=conf.LANG_ZH_CN, i1_message=u"取消", i1_type="task_status_code"))
        
        i18ns.append(I18n(i1_key="task_code_task", i1_locale=conf.LANG_EN, i1_message=u"Task", i1_type="task_type_code"))
        i18ns.append(I18n(i1_key="task_code_task", i1_locale=conf.LANG_ZH_CN, i1_message=u"任务", i1_type="task_type_code"))
        i18ns.append(I18n(i1_key="task_code_issue", i1_locale=conf.LANG_EN, i1_message=u"Issue", i1_type="task_type_code"))
        i18ns.append(I18n(i1_key="task_code_issue", i1_locale=conf.LANG_ZH_CN, i1_message=u"问题", i1_type="task_type_code"))
        i18ns.append(I18n(i1_key="task_code_risk", i1_locale=conf.LANG_EN, i1_message=u"Risk", i1_type="task_type_code"))
        i18ns.append(I18n(i1_key="task_code_risk", i1_locale=conf.LANG_ZH_CN, i1_message=u"风险", i1_type="task_type_code"))
        i18ns.append(I18n(i1_key="task_code_meeting", i1_locale=conf.LANG_EN, i1_message=u"Meeting", i1_type="task_type_code"))
        i18ns.append(I18n(i1_key="task_code_meeting", i1_locale=conf.LANG_ZH_CN, i1_message=u"会议", i1_type="task_type_code"))
        
        i18ns.append(I18n(i1_key="task_code_p1", i1_locale=conf.LANG_EN, i1_message=u"P1", i1_type="task_priority_code"))
        i18ns.append(I18n(i1_key="task_code_p1", i1_locale=conf.LANG_ZH_CN, i1_message=u"P1", i1_type="task_priority_code"))
        i18ns.append(I18n(i1_key="task_code_p2", i1_locale=conf.LANG_EN, i1_message=u"P2", i1_type="task_priority_code"))
        i18ns.append(I18n(i1_key="task_code_p2", i1_locale=conf.LANG_ZH_CN, i1_message=u"P2", i1_type="task_priority_code"))
        i18ns.append(I18n(i1_key="task_code_p3", i1_locale=conf.LANG_EN, i1_message=u"P3", i1_type="task_priority_code"))
        i18ns.append(I18n(i1_key="task_code_p3", i1_locale=conf.LANG_ZH_CN, i1_message=u"P3", i1_type="task_priority_code"))
        i18ns.append(I18n(i1_key="task_code_p4", i1_locale=conf.LANG_EN, i1_message=u"P4", i1_type="task_priority_code"))
        i18ns.append(I18n(i1_key="task_code_p4", i1_locale=conf.LANG_ZH_CN, i1_message=u"P4", i1_type="task_priority_code"))
        i18ns.append(I18n(i1_key="task_code_p5", i1_locale=conf.LANG_EN, i1_message=u"P5", i1_type="task_priority_code"))
        i18ns.append(I18n(i1_key="task_code_p5", i1_locale=conf.LANG_ZH_CN, i1_message=u"P5", i1_type="task_priority_code"))
        
        i18ns.append(I18n(i1_key="task_label_worksheet", i1_locale=conf.LANG_EN, i1_message=u"Worksheet"))
        i18ns.append(I18n(i1_key="task_label_worksheet", i1_locale=conf.LANG_ZH_CN, i1_message=u"工作清单"))
        i18ns.append(I18n(i1_key="task_label_myworksheets", i1_locale=conf.LANG_EN, i1_message=u"My Task List"))
        i18ns.append(I18n(i1_key="task_label_myworksheets", i1_locale=conf.LANG_ZH_CN, i1_message=u"我的工作清单"))
        i18ns.append(I18n(i1_key="task_label_workbasket", i1_locale=conf.LANG_EN, i1_message=u"Work Basket"))
        i18ns.append(I18n(i1_key="task_label_workbasket", i1_locale=conf.LANG_ZH_CN, i1_message=u"工作篮"))
        i18ns.append(I18n(i1_key="task_label_recyclebin", i1_locale=conf.LANG_EN, i1_message=u"Recyclebin"))
        i18ns.append(I18n(i1_key="task_label_recyclebin", i1_locale=conf.LANG_ZH_CN, i1_message=u"回收站"))
        i18ns.append(I18n(i1_key="task_label_task", i1_locale=conf.LANG_EN, i1_message=u"Task"))
        i18ns.append(I18n(i1_key="task_label_task", i1_locale=conf.LANG_ZH_CN, i1_message=u"工作事项"))
        i18ns.append(I18n(i1_key="task_label_tasksearch", i1_locale=conf.LANG_EN, i1_message=u"Task Search"))
        i18ns.append(I18n(i1_key="task_label_tasksearch", i1_locale=conf.LANG_ZH_CN, i1_message=u"搜索工作事项"))
        i18ns.append(I18n(i1_key="task_label_worksheetname", i1_locale=conf.LANG_EN, i1_message=u"Worksheet Name"))
        i18ns.append(I18n(i1_key="task_label_worksheetname", i1_locale=conf.LANG_ZH_CN, i1_message=u"工作清单名称"))
        i18ns.append(I18n(i1_key="task_label_tasksubject", i1_locale=conf.LANG_EN, i1_message=u"Subject"))
        i18ns.append(I18n(i1_key="task_label_tasksubject", i1_locale=conf.LANG_ZH_CN, i1_message=u"主题"))
        i18ns.append(I18n(i1_key="task_label_taskdescription", i1_locale=conf.LANG_EN, i1_message=u"Description"))
        i18ns.append(I18n(i1_key="task_label_taskdescription", i1_locale=conf.LANG_ZH_CN, i1_message=u"描述"))
        i18ns.append(I18n(i1_key="task_label_taskassigneekey", i1_locale=conf.LANG_EN, i1_message=u"Assignee"))
        i18ns.append(I18n(i1_key="task_label_taskassigneekey", i1_locale=conf.LANG_ZH_CN, i1_message=u"责任人"))
        i18ns.append(I18n(i1_key="task_label_worksheetkey", i1_locale=conf.LANG_EN, i1_message=u"Worksheet"))
        i18ns.append(I18n(i1_key="task_label_worksheetkey", i1_locale=conf.LANG_ZH_CN, i1_message=u"工作清单"))
        i18ns.append(I18n(i1_key="task_label_tasktypecode", i1_locale=conf.LANG_EN, i1_message=u"Task Type"))        
        i18ns.append(I18n(i1_key="task_label_tasktypecode", i1_locale=conf.LANG_ZH_CN, i1_message=u"分类"))        
        i18ns.append(I18n(i1_key="task_label_taskprioritycode", i1_locale=conf.LANG_EN, i1_message=u"Priority"))
        i18ns.append(I18n(i1_key="task_label_taskprioritycode", i1_locale=conf.LANG_ZH_CN, i1_message=u"优先级"))
        i18ns.append(I18n(i1_key="task_label_taskstatuscode", i1_locale=conf.LANG_EN, i1_message=u"Status"))
        i18ns.append(I18n(i1_key="task_label_taskstatuscode", i1_locale=conf.LANG_ZH_CN, i1_message=u"状态"))
        i18ns.append(I18n(i1_key="task_label_taskkey", i1_locale=conf.LANG_EN, i1_message=u"Task Key"))
        i18ns.append(I18n(i1_key="task_label_taskkey", i1_locale=conf.LANG_ZH_CN, i1_message=u"任务Key"))
        i18ns.append(I18n(i1_key="task_label_duestartdate", i1_locale=conf.LANG_EN, i1_message=u"Plan Start Date"))
        i18ns.append(I18n(i1_key="task_label_duestartdate", i1_locale=conf.LANG_ZH_CN, i1_message=u"计划开始日期"))
        i18ns.append(I18n(i1_key="task_label_duefinishdate", i1_locale=conf.LANG_EN, i1_message=u"Plan Finish Date"))
        i18ns.append(I18n(i1_key="task_label_duefinishdate", i1_locale=conf.LANG_ZH_CN, i1_message=u"计划完成日期"))
        i18ns.append(I18n(i1_key="task_label_duestarttime", i1_locale=conf.LANG_EN, i1_message=u"Plan Start Time"))
        i18ns.append(I18n(i1_key="task_label_duestarttime", i1_locale=conf.LANG_ZH_CN, i1_message=u"计划开始时间"))
        i18ns.append(I18n(i1_key="task_label_duefinishtime", i1_locale=conf.LANG_EN, i1_message=u"Plan Finish Time"))
        i18ns.append(I18n(i1_key="task_label_duefinishtime", i1_locale=conf.LANG_ZH_CN, i1_message=u"计划完成时间"))
        i18ns.append(I18n(i1_key="task_label_shortduestartdate", i1_locale=conf.LANG_EN, i1_message=u"Plan Start"))
        i18ns.append(I18n(i1_key="task_label_shortduestartdate", i1_locale=conf.LANG_ZH_CN, i1_message=u"计划开始"))
        i18ns.append(I18n(i1_key="task_label_shortduefinishdate", i1_locale=conf.LANG_EN, i1_message=u"Plan Finish"))
        i18ns.append(I18n(i1_key="task_label_shortduefinishdate", i1_locale=conf.LANG_ZH_CN, i1_message=u"计划完成"))
        i18ns.append(I18n(i1_key="task_label_actualprogress", i1_locale=conf.LANG_EN, i1_message=u"Actual Progress(%)"))
        i18ns.append(I18n(i1_key="task_label_actualprogress", i1_locale=conf.LANG_ZH_CN, i1_message=u"实际完成进度(%)"))
        i18ns.append(I18n(i1_key="task_label_planprogress", i1_locale=conf.LANG_EN, i1_message=u"Plan Progress(%)"))
        i18ns.append(I18n(i1_key="task_label_planprogress", i1_locale=conf.LANG_ZH_CN, i1_message=u"计划完成进度(%)"))
        i18ns.append(I18n(i1_key="task_label_planprogresstips", i1_locale=conf.LANG_EN, i1_message=u"Plan Progress(%) + Delay Days - Caculated by due start and finish date"))
        i18ns.append(I18n(i1_key="task_label_planprogresstips", i1_locale=conf.LANG_ZH_CN, i1_message=u"按计划应该完成进度(%) + 延迟天数 - 系统会根据计划开始和结束日期自动计算, 如果没有填写计划开始和结束日期会显示NA"))
        i18ns.append(I18n(i1_key="task_label_taskcomment", i1_locale=conf.LANG_EN, i1_message=u"Task Comment"))
        i18ns.append(I18n(i1_key="task_label_taskcomment", i1_locale=conf.LANG_ZH_CN, i1_message=u"工作事项日志"))
        i18ns.append(I18n(i1_key="task_label_progress", i1_locale=conf.LANG_EN, i1_message=u"Progress(Actual/Plan)"))
        i18ns.append(I18n(i1_key="task_label_progress", i1_locale=conf.LANG_ZH_CN, i1_message=u"进度(实际/计划)"))
        i18ns.append(I18n(i1_key="task_label_shortprogress", i1_locale=conf.LANG_EN, i1_message=u"Progress(%)"))
        i18ns.append(I18n(i1_key="task_label_shortprogress", i1_locale=conf.LANG_ZH_CN, i1_message=u"进度(%)"))
        i18ns.append(I18n(i1_key="task_label_addacomment", i1_locale=conf.LANG_EN, i1_message=u"add a comment"))
        i18ns.append(I18n(i1_key="task_label_addacomment", i1_locale=conf.LANG_ZH_CN, i1_message=u"新增工作日志"))
        i18ns.append(I18n(i1_key="task_label_nocomment", i1_locale=conf.LANG_EN, i1_message=u"Zero Comments"))
        i18ns.append(I18n(i1_key="task_label_nocomment", i1_locale=conf.LANG_ZH_CN, i1_message=u"这个任务暂时没有工作日志。"))
        i18ns.append(I18n(i1_key="task_label_tccontent", i1_locale=conf.LANG_EN, i1_message=u"Comment"))
        i18ns.append(I18n(i1_key="task_label_tccontent", i1_locale=conf.LANG_ZH_CN, i1_message=u"工作日志"))
        
        i18ns.append(I18n(i1_key="task_action_emptyrecyclebin", i1_locale=conf.LANG_EN, i1_message=u"Empty Recycle Bin"))
        i18ns.append(I18n(i1_key="task_action_emptyrecyclebin", i1_locale=conf.LANG_ZH_CN, i1_message=u"清空回收站"))
        i18ns.append(I18n(i1_key="task_action_addworksheet", i1_locale=conf.LANG_EN, i1_message=u"Add Worksheet"))
        i18ns.append(I18n(i1_key="task_action_addworksheet", i1_locale=conf.LANG_ZH_CN, i1_message=u"新建工作清单"))
        i18ns.append(I18n(i1_key="task_action_updateworksheet", i1_locale=conf.LANG_EN, i1_message=u"Rename Worksheet"))
        i18ns.append(I18n(i1_key="task_action_updateworksheet", i1_locale=conf.LANG_ZH_CN, i1_message=u"重命名工作清单"))
        i18ns.append(I18n(i1_key="task_action_deleteworksheet", i1_locale=conf.LANG_EN, i1_message=u"Delete Worksheet"))
        i18ns.append(I18n(i1_key="task_action_deleteworksheet", i1_locale=conf.LANG_ZH_CN, i1_message=u"删除工作清单"))

        i18ns.append(I18n(i1_key="task_action_addtask", i1_locale=conf.LANG_EN, i1_message=u"Add Task"))
        i18ns.append(I18n(i1_key="task_action_addtask", i1_locale=conf.LANG_ZH_CN, i1_message=u"新建工作事项"))
        i18ns.append(I18n(i1_key="task_action_recovertask", i1_locale=conf.LANG_EN, i1_message=u"Recover Task"))
        i18ns.append(I18n(i1_key="task_action_recovertask", i1_locale=conf.LANG_ZH_CN, i1_message=u"恢复工作事项"))
        i18ns.append(I18n(i1_key="task_action_permanentdelete", i1_locale=conf.LANG_EN, i1_message=u"Permanent Delete Task"))
        i18ns.append(I18n(i1_key="task_action_permanentdelete", i1_locale=conf.LANG_ZH_CN, i1_message=u"永久删除工作事项"))
        i18ns.append(I18n(i1_key="task_action_addtaskcomment", i1_locale=conf.LANG_EN, i1_message=u"Add Comment"))
        i18ns.append(I18n(i1_key="task_action_addtaskcomment", i1_locale=conf.LANG_ZH_CN, i1_message=u"新建工作事项日志"))
        
        i18ns.append(I18n(i1_key="task_confirm_emptyrecyclebin", i1_locale=conf.LANG_EN, i1_message=u"Do you confirm to clear up recycle bin ?"))
        i18ns.append(I18n(i1_key="task_confirm_emptyrecyclebin", i1_locale=conf.LANG_ZH_CN, i1_message=u"你确定要清空回收站吗？"))
        i18ns.append(I18n(i1_key="task_confirm_deletetask", i1_locale=conf.LANG_EN, i1_message=u"Do you confirm to delete this task ?"))
        i18ns.append(I18n(i1_key="task_confirm_deletetask", i1_locale=conf.LANG_ZH_CN, i1_message=u"你确定要删除这个工作事项吗？"))
        i18ns.append(I18n(i1_key="task_confirm_permanentdeletetask", i1_locale=conf.LANG_EN, i1_message=u"Do you confirm to delete this task permanently ?"))
        i18ns.append(I18n(i1_key="task_confirm_permanentdeletetask", i1_locale=conf.LANG_ZH_CN, i1_message=u"你确定要永久删除这个工作事项吗？"))
        i18ns.append(I18n(i1_key="task_confirm_movetask", i1_locale=conf.LANG_EN, i1_message=u"Do you confirm to move this task to worksheet {{worksheet}}?"))
        i18ns.append(I18n(i1_key="task_confirm_movetask", i1_locale=conf.LANG_ZH_CN, i1_message=u"你确定要移动这个工作事项到{{worksheet}}吗？"))
        i18ns.append(I18n(i1_key="task_confirm_recovertask", i1_locale=conf.LANG_EN, i1_message=u"Do you confirm to recover this task to work basket?"))
        i18ns.append(I18n(i1_key="task_confirm_recovertask", i1_locale=conf.LANG_ZH_CN, i1_message=u"你确定要恢复这个笔记到{{notebook}}吗？"))
        i18ns.append(I18n(i1_key="task_confirm_emptytrash", i1_locale=conf.LANG_EN, i1_message=u"Do you confirm to empty the recycle bin ?"))
        i18ns.append(I18n(i1_key="task_confirm_emptytrash", i1_locale=conf.LANG_ZH_CN, i1_message=u"你确定要清空回收站吗？"))
        
        i18ns.append(I18n(i1_key="task_confirm_worksheet_delete", i1_locale=conf.LANG_EN, i1_message=u"The tasks in this worksheet will be deleted also, do you confirm to delete this worksheet."))
        i18ns.append(I18n(i1_key="task_confirm_worksheet_delete", i1_locale=conf.LANG_ZH_CN, i1_message=u"工作清单中的工作事项将被同步删除， 你确认要删除吗？"))
        i18ns.append(I18n(i1_key="task_error_trashed_update", i1_locale=conf.LANG_EN, i1_message=u"You can't update the tasks which are in trash."))
        i18ns.append(I18n(i1_key="task_error_trashed_update", i1_locale=conf.LANG_ZH_CN, i1_message=u"工作事项在回收站中，不能编辑！"))
        i18ns.append(I18n(i1_key="task_error_pendingsave", i1_locale=conf.LANG_EN, i1_message=u"Task is not saved, please save first then go to another task."))
        i18ns.append(I18n(i1_key="task_error_pendingsave", i1_locale=conf.LANG_ZH_CN, i1_message=u"工作还没有保存，请先保存工作再切换到其它工作！"))
        
        i18ns.append(I18n(i1_key="task_confirm_deletetaskcomment", i1_locale=conf.LANG_EN, i1_message=u"Do you confirm to delete this task comment ?"))
        i18ns.append(I18n(i1_key="task_confirm_deletetaskcomment", i1_locale=conf.LANG_ZH_CN, i1_message=u"你确定要删除这个工作事项日志吗？"))
  
        return i18ns
